import swaggerAutogen from 'swagger-autogen';
import routes from './src/routes';

const doc = {
  info: {
    version: '1.0.0',
    title: 'Planta & Hidro API',
    description:
      'Documentation automatically generated by the <b>swagger-autogen</b> module.',
  },
  host: 'localhost:3333',
  basePath: '/',
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
};

const outputFile = './swagger-output.json';
const endpointsFiles = ['./src/routes.js'];

swaggerAutogen()(outputFile, endpointsFiles, doc).then(async () => {
  await routes;
});
